// 周报月报存储管理逻辑
const REPORT_KEY = 'knit-reports';

function loadReports() {
  try {
    return JSON.parse(localStorage.getItem(REPORT_KEY)) || [];
  } catch {
    return [];
  }
}

function saveReports(reports) {
  localStorage.setItem(REPORT_KEY, JSON.stringify(reports));
}

function renderReportList() {
  const list = document.getElementById('reportList');
  let filter = 'all';
  const group = document.getElementById('reportFilterGroup');
  if (group) {
    const activeBtn = group.querySelector('.is-active');
    filter = activeBtn?.dataset.value || 'all';
  }
  let reports = loadReports();
  if (filter === 'week') reports = reports.filter(r => r.type === 'week');
  if (filter === 'month') reports = reports.filter(r => r.type === 'month');
  if (!list) return;
  if (reports.length === 0) {
    list.innerHTML = '<div class="empty-tip">暂无报告</div>';
    return;
  }
  list.innerHTML = reports.map((r, i) => `
    <article class="report-card ${r.type === 'week' ? 'is-week' : 'is-month'}">
      <header class="report-card-head">
        <div class="report-card-title-wrap" style="flex:1; display:flex; align-items:center; gap:10px; min-width:0;">
          <h3 class="report-title">${r.title || '(无标题)'}</h3>
        </div>
        <div style="display:flex; flex-direction:row; align-items:center; gap:8px; min-width:48px;">
          <span class="report-type">${r.type === 'week' ? '周报' : '月报'}</span>
          <div class="report-card-actions report-card-actions-top">
            <button class="btn ghost icon-btn" type="button" onclick="editReport(${i})" title="编辑报告" aria-label="编辑报告">✎</button>
            <button class="btn ghost icon-btn danger-icon" type="button" onclick="deleteReport(${i})" title="删除报告" aria-label="删除报告">🗑</button>
          </div>
        </div>
      </header>
      <div class="report-card-body">${r.content.replace(/\n/g, '<br>')}</div>
    </article>
  `).join('');
}

function showReportForm(editIdx = null) {
  document.getElementById('reportFormPanel').style.display = '';
  document.getElementById('reportList').style.display = 'none';
  document.getElementById('reportFormTitle').textContent = editIdx === null ? '新建报告' : '编辑报告';
  const form = document.getElementById('reportForm');
  form.reset();
  form.dataset.editIdx = editIdx;
  if (editIdx !== null) {
    const r = loadReports()[editIdx];
    form.reportType.value = r.type;
    form.reportTitle.value = r.title;
    form.reportContent.value = r.content;
  }
}

function hideReportForm() {
  document.getElementById('reportFormPanel').style.display = 'none';
  document.getElementById('reportList').style.display = '';
}

function editReport(idx) {
  showReportForm(idx);
}

function deleteReport(idx) {
  if (!confirm('确定要删除该报告吗？')) return;
  const reports = loadReports();
  reports.splice(idx, 1);
  saveReports(reports);
  renderReportList();
}


// 自动生成周报月报（每次进入页面时检测）
function autoGenerateReports() {
  const reports = loadReports();
  let changed = false;

  // 每次进入页面都刷新“上周周报”（若不存在则创建）
  const lastWeek = getLastWeekRange();
  const weekKey = `week-${lastWeek.start}`;
  {
    const content = autoSummary('week', lastWeek.start, lastWeek.end);
    const title = getWeekReportTitle(lastWeek.start, lastWeek.end);
    const idx = reports.findIndex(r => r.type === 'week' && r.date === weekKey);
    if (idx >= 0) {
      reports[idx] = { ...reports[idx], title, content, autoGenerated: true };
    } else {
      reports.unshift({ type: 'week', title, content, date: weekKey, autoGenerated: true });
    }
    changed = true;
  }

  // 每次进入页面都刷新“上月月报”（若不存在则创建）
  const lastMonth = getLastMonthRange();
  const monthKey = `month-${lastMonth.start}`;
  {
    const content = autoSummary('month', lastMonth.start, lastMonth.end);
    const title = getMonthReportTitle(lastMonth.start);
    const idx = reports.findIndex(r => r.type === 'month' && r.date === monthKey);
    if (idx >= 0) {
      reports[idx] = { ...reports[idx], title, content, autoGenerated: true };
    } else {
      reports.unshift({ type: 'month', title, content, date: monthKey, autoGenerated: true });
    }
    changed = true;
  }

  if (changed) saveReports(reports);
}

function toLocalDateKey(date) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function toNonNegative(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return 0;
  return n < 0 ? 0 : n;
}

function formatDuration(seconds) {
  const total = toNonNegative(seconds);
  if (total <= 0) return '0小时';
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  if (h > 0 && m > 0) return `${h}小时${m}分`;
  if (h > 0) return `${h}小时`;
  return `${m}分`;
}

function loadProjectsForReport() {
  const keys = ['knit-helper-state', 'knit-project-storage', 'knit-stats-storage', 'knit-stats'];
  for (const key of keys) {
    try {
      const raw = localStorage.getItem(key);
      if (!raw) continue;
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
      if (parsed && Array.isArray(parsed.projects)) return parsed.projects;
    } catch {}
  }
  return [];
}

function loadYarnForReport() {
  try {
    const raw = localStorage.getItem('knit-yarn-storage');
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function collectPeriodStats(start, end) {
  const projects = loadProjectsForReport();
  const yarnItems = loadYarnForReport();

  let totalSeconds = 0;
  let totalRows = 0;
  let yarnUsed = 0;
  const activeDays = new Set();
  const projectSummaries = [];

  projects.forEach((project) => {
    const daily = project && typeof project.dailyStats === 'object' ? project.dailyStats : {};
    let projectSeconds = 0;
    let projectRows = 0;

    Object.entries(daily).forEach(([date, stat]) => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return;
      if (date < start || date > end) return;
      const sec = toNonNegative(stat && stat.seconds);
      const rows = toNonNegative(stat && stat.rows);
      projectSeconds += sec;
      // 行数只累计到有计时记录的日期，避免无计时历史数据混入该周期
      if (sec > 0) {
        projectRows += rows;
        activeDays.add(date);
      }
    });

    // 仅该周期有计时的项目进入统计
    if (projectSeconds > 0) {
      projectSummaries.push({
        name: String(project.projectName || project.name || '未命名项目'),
        seconds: projectSeconds,
        rows: projectRows,
      });
    }

    totalSeconds += projectSeconds;
    totalRows += projectRows;
  });

  yarnItems.forEach((item) => {
    const usedLog = Array.isArray(item && item.usedLog) ? item.usedLog : [];
    usedLog.forEach((log) => {
      const date = String(log && log.date || '');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return;
      if (date < start || date > end) return;
      yarnUsed += toNonNegative(log && log.used);
    });
  });

  projectSummaries.sort((a, b) => b.seconds - a.seconds || b.rows - a.rows);
  const topProjects = projectSummaries.slice(0, 3);

  return {
    totalSeconds,
    totalRows,
    yarnUsed,
    activeDays: activeDays.size,
    activeProjects: projectSummaries.length,
    topProjects,
  };
}

function getLastWeekRange() {
  const now = new Date();
  const day = now.getDay() || 7;
  const end = new Date(now.getFullYear(), now.getMonth(), now.getDate() - day);
  const start = new Date(end.getFullYear(), end.getMonth(), end.getDate() - 6);
  return {
    start: toLocalDateKey(start),
    end: toLocalDateKey(end)
  };
}
function getLastMonthRange() {
  const now = new Date();
  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const start = new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 1);
  const end = new Date(lastMonth.getFullYear(), lastMonth.getMonth() + 1, 0);
  return {
    start: toLocalDateKey(start),
    end: toLocalDateKey(end)
  };
}

function getIsoWeekNumber(date) {
  const target = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = target.getUTCDay() || 7;
  target.setUTCDate(target.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(target.getUTCFullYear(), 0, 1));
  return Math.ceil((((target - yearStart) / 86400000) + 1) / 7);
}

function getWeekReportTitle(start, end) {
  const weekNo = getIsoWeekNumber(new Date(`${start}T12:00:00`));
  const endYear = new Date(`${end}T12:00:00`).getFullYear();
  return `${endYear}年第${weekNo}周报告（${start}~${end}）`;
}

function getMonthReportTitle(start) {
  const [year, month] = String(start).split('-');
  const monthNo = Number(month);
  const end = new Date(Number(year), monthNo, 0);
  const endKey = `${end.getFullYear()}-${String(end.getMonth() + 1).padStart(2, '0')}-${String(end.getDate()).padStart(2, '0')}`;
  return `${year}年${monthNo}月报告（${start}~${endKey}）`;
}
// 简单自动汇总（可扩展为统计分析）
function autoSummary(type, start, end) {
  const stats = collectPeriodStats(start, end);
  const lines = [];
  lines.push('<div class="report-section-title">数据回顾</div>');
  lines.push(`- 周期内编织时长：${formatDuration(stats.totalSeconds)}`);
  lines.push(`- 周期内完成行数：${stats.totalRows} 行`);
  lines.push(`- 活跃天数：${stats.activeDays} 天`);
  lines.push(`- 活跃项目：${stats.activeProjects} 个`);
  lines.push(`- 毛线消耗：${stats.yarnUsed.toFixed(1)} g`);

  lines.push('<div class="report-section-title">投入项目</div>');
  if (stats.topProjects.length > 0) {
    stats.topProjects.forEach((p, idx) => {
      lines.push(`${idx + 1}. ${p.name}：${formatDuration(p.seconds)}，${p.rows} 行`);
    });
  } else {
    lines.push('暂无投入项目。');
  }

  if (stats.totalSeconds <= 0 && stats.totalRows <= 0) {
    lines.push('');
    lines.push('本周期暂无有效编织记录。');
    lines.push('建议：先在项目页开启计时并更新行数，系统会在下次自动生成时产出完整报告。');
  }

  return lines.join('\n');
}

document.addEventListener('DOMContentLoaded', () => {
  autoGenerateReports();
  renderReportList();
  if (window.setupCloudSync) window.setupCloudSync();
  document.getElementById('addReportBtn').onclick = () => showReportForm();
  document.getElementById('cancelReportBtn').onclick = hideReportForm;
  document.getElementById('reportForm').onsubmit = function (e) {
    e.preventDefault();
    const type = this.reportType.value;
    const title = this.reportTitle.value.trim();
    const content = this.reportContent.value.trim();
    const date = new Date().toISOString().slice(0, 10);
    const reports = loadReports();
    const idx = this.dataset.editIdx;
    if (idx === '' || idx === undefined) {
      reports.unshift({ type, title, content, date });
    } else {
      reports[idx] = { type, title, content, date };
    }
    saveReports(reports);
    hideReportForm();
    renderReportList();
  };
  const group = document.getElementById('reportFilterGroup');
  if (group) {
    group.addEventListener('click', (e) => {
      if (e.target.classList.contains('report-filter-btn')) {
        group.querySelectorAll('.report-filter-btn').forEach(btn => btn.classList.remove('is-active'));
        e.target.classList.add('is-active');
        renderReportList();
      }
    });
  }
});
